import { dirname, join } from 'path';
import { mkdir, stat, writeFile } from 'fs/promises';
import { resolveProjectById, getProjectById } from './projects.js';
import { buildTree } from './requirements.js';
import type { TreeNode } from '../types/project.js';

interface Branding {
  primary: string;
  secondary: string;
}

interface ScaffoldResult {
  success: boolean;
  outputPath: string;
  filesCreated: number;
  logs: string[];
}

/* ------------------------------------------------------------------ */
/*  Helper: convert requirement title to URL-safe slug                 */
/* ------------------------------------------------------------------ */

function slugify(name: string): string {
  return name
    .replace(/^[A-Z]+-[\d.]+[:\s]*/i, '') // strip prefix like "SOL-1: "
    .trim()
    .toLowerCase()
    .replace(/[äÄ]/g, 'ae')
    .replace(/[öÖ]/g, 'oe')
    .replace(/[üÜ]/g, 'ue')
    .replace(/ß/g, 'ss')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'unnamed';
}

/* ------------------------------------------------------------------ */
/*  Helper: safe string for JSX/TS templates                           */
/* ------------------------------------------------------------------ */

function safe(str: string, maxLen = 80): string {
  return str.replace(/'/g, "\\'").replace(/`/g, "'").slice(0, maxLen);
}

/* ------------------------------------------------------------------ */
/*  Helper: PascalCase identifier from a slug                          */
/* ------------------------------------------------------------------ */

function pascal(slug: string): string {
  return slug
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/* ------------------------------------------------------------------ */
/*  File content generators                                            */
/* ------------------------------------------------------------------ */

function genPackageJson(projectName: string): string {
  return JSON.stringify(
    {
      name: projectName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
      },
      dependencies: {
        next: '^15.0.0',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
      },
      devDependencies: {
        typescript: '^5.7.0',
        '@types/node': '^22.0.0',
        '@types/react': '^19.0.0',
        '@types/react-dom': '^19.0.0',
      },
    },
    null,
    2
  ) + '\n';
}

function genTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    },
    null,
    2
  ) + '\n';
}

function genNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;
`;
}

function genGitignore(): string {
  return `node_modules/
.next/
out/
dist/
.env*.local
*.tsbuildinfo
next-env.d.ts
`;
}

function genGlobalsCSS(brand: Branding): string {
  return `:root {
  --color-bg: #0d1117;
  --color-bg2: #161b22;
  --color-text-primary: #e6edf3;
  --color-text-secondary: #8b949e;
  --color-text-tertiary: #6e7681;
  --color-brand-gold: ${brand.primary};
  --color-brand-anthracite: ${brand.secondary};
  --color-border: #30363d;
  --font-sans: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
  --font-mono: 'JetBrains Mono', monospace;
  --radius-md: 8px;
  --radius-lg: 12px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-5: 20px;
  --space-6: 24px;
  --space-8: 32px;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: var(--font-sans);
  background: var(--color-bg);
  color: var(--color-text-primary);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}

a { color: var(--color-brand-gold); text-decoration: none; }
a:hover { text-decoration: underline; }

code, pre {
  font-family: var(--font-mono);
  font-size: 13px;
}
`;
}

function genRootLayout(projectName: string, sols: TreeNode[]): string {
  const navLinks = sols
    .map((sol) => {
      const slug = slugify(sol.title);
      const label = safe(sol.title, 30);
      return `            <a href="/${slug}">${sol.id}: ${label}</a>`;
    })
    .join('\n');

  return `// @generated by ARQITEKT Scaffold
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${safe(projectName)}',
  description: 'Generated by ARQITEKT Product Factory',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de">
      <body>
        <header style={{ background: 'var(--color-bg2)', borderBottom: '1px solid var(--color-border)', padding: '0 var(--space-6)', height: 56, display: 'flex', alignItems: 'center', gap: 'var(--space-6)' }}>
          <h1 style={{ fontSize: 18, fontWeight: 700, color: 'var(--color-brand-gold)', whiteSpace: 'nowrap' }}>
            ${safe(projectName)}
          </h1>
          <nav style={{ display: 'flex', gap: 'var(--space-4)', overflowX: 'auto' }}>
${navLinks}
          </nav>
        </header>
        <main style={{ maxWidth: 1200, margin: '0 auto', padding: 'var(--space-6)' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
`;
}

function genLandingPage(projectName: string, bcTitle: string): string {
  return `// @generated by ARQITEKT Scaffold
// Landing Page — from Business Case

export default function Home() {
  return (
    <div style={{ padding: 'var(--space-8) 0' }}>
      <h1 style={{ fontSize: 28, fontWeight: 700, color: 'var(--color-brand-gold)', marginBottom: 'var(--space-4)' }}>
        ${safe(projectName)}
      </h1>
      <p style={{ fontSize: 15, color: 'var(--color-text-secondary)', maxWidth: 720, lineHeight: 1.8 }}>
        ${safe(bcTitle, 200)}
      </p>
      <p style={{ marginTop: 'var(--space-6)', color: 'var(--color-text-tertiary)', fontStyle: 'italic' }}>
        Generated by ARQITEKT Product Factory
      </p>
    </div>
  );
}
`;
}

function genSolLayout(sol: TreeNode): string {
  const usLinks = sol.children
    .filter((c) => c.type === 'US')
    .map((us) => {
      const solSlug = slugify(sol.title);
      const usSlug = slugify(us.title);
      const label = safe(us.title, 40);
      return `            <a href="/${solSlug}/${usSlug}">${us.id}: ${label}</a>`;
    })
    .join('\n');

  const fnName = `Sol${pascal(slugify(sol.title))}Layout`;

  return `// @generated by ARQITEKT Scaffold
// Solution Layout: ${sol.id} — ${safe(sol.title)}

export default function ${fnName}({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ display: 'grid', gridTemplateColumns: '240px 1fr', gap: 'var(--space-6)', minHeight: 'calc(100vh - 100px)' }}>
      <aside style={{ borderRight: '1px solid var(--color-border)', paddingRight: 'var(--space-4)' }}>
        <h2 style={{ fontSize: 15, fontWeight: 600, color: 'var(--color-brand-gold)', marginBottom: 'var(--space-4)' }}>
          ${sol.id}: ${safe(sol.title, 60)}
        </h2>
        <nav style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
${usLinks}
        </nav>
      </aside>
      <section style={{ minWidth: 0 }}>
        {children}
      </section>
    </div>
  );
}
`;
}

function genSolIndexPage(sol: TreeNode): string {
  const fnName = `Sol${pascal(slugify(sol.title))}Page`;

  return `// @generated by ARQITEKT Scaffold
// Solution Index: ${sol.id}

export default function ${fnName}() {
  return (
    <div>
      <h1 style={{ fontSize: 22, fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 'var(--space-3)' }}>
        ${sol.id}: ${safe(sol.title)}
      </h1>
      <p style={{ color: 'var(--color-text-secondary)' }}>
        Select a User Story from the sidebar.
      </p>
    </div>
  );
}
`;
}

function genUSPage(us: TreeNode, sol: TreeNode): string {
  const cmps = us.children.filter((c) => c.type === 'CMP');

  const imports = cmps
    .map((cmp) => {
      const cmpSlug = slugify(cmp.title);
      const cmpName = pascal(cmpSlug);
      return `import ${cmpName} from '@/components/${cmpSlug}';`;
    })
    .join('\n');

  const renders = cmps
    .map((cmp) => {
      const cmpName = pascal(slugify(cmp.title));
      return `        <${cmpName} />`;
    })
    .join('\n');

  const fnName = `US${pascal(slugify(us.title))}Page`;

  return `// @generated by ARQITEKT Scaffold
// Page: ${us.id} — ${safe(us.title)}
// Parent: ${sol.id}
${imports ? imports + '\n' : ''}
export default function ${fnName}() {
  return (
    <div style={{ padding: 'var(--space-4) 0' }}>
      <h1 style={{ fontSize: 22, fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 'var(--space-6)' }}>
        ${us.id}: ${safe(us.title)}
      </h1>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)' }}>
${renders || '        <p>No components defined.</p>'}
      </div>
    </div>
  );
}
`;
}

function genComponent(cmp: TreeNode): string {
  const cmpSlug = slugify(cmp.title);
  const cmpName = pascal(cmpSlug);

  const fns = cmp.children.filter((c) => c.type === 'FN');
  const fnImports = fns
    .map((fn) => {
      const fnSlug = slugify(fn.title);
      const fnIdent = fnSlug.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
      return `import { ${fnIdent} } from '@/lib/${fnSlug}';`;
    })
    .join('\n');

  return `// @generated by ARQITEKT Scaffold
// Component: ${cmp.id} — ${safe(cmp.title)}
// TODO: ARQITEKT — implement ${safe(cmp.title)}
'use client';
${fnImports ? '\n' + fnImports + '\n' : ''}
export default function ${cmpName}() {
  return (
    <div style={{ background: 'var(--color-bg2)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-lg)', padding: 'var(--space-5)' }}>
      <h3 style={{ fontSize: 15, fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
        ${safe(cmp.title)}
      </h3>
      <p style={{ color: 'var(--color-text-tertiary)', fontStyle: 'italic' }}>
        TODO: implement ${cmp.id}
      </p>
    </div>
  );
}
`;
}

function genFunction(fn: TreeNode, parentCmp: TreeNode): string {
  const fnSlug = slugify(fn.title);
  const fnIdent = fnSlug.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

  return `// @generated by ARQITEKT Scaffold
// Function: ${fn.id} — ${safe(fn.title)}
// Parent: ${parentCmp.id}
// TODO: ARQITEKT — implement ${safe(fn.title)}

/**
 * ${fn.title}
 *
 * @param args - Function arguments (to be typed during implementation)
 * @returns Result (to be typed during implementation)
 */
export function ${fnIdent}(...args: unknown[]): unknown {
  // TODO: ARQITEKT — implement ${safe(fn.title)}
  throw new Error('Not implemented: ${fn.id}');
}
`;
}

/* ------------------------------------------------------------------ */
/*  Async file writer with directory creation                          */
/* ------------------------------------------------------------------ */

async function writeFileWithDir(
  filePath: string,
  content: string,
  logs: string[]
): Promise<void> {
  const dir = dirname(filePath);
  await mkdir(dir, { recursive: true });
  await writeFile(filePath, content, 'utf-8');
  logs.push(`  created: ${filePath}`);
}

/* ------------------------------------------------------------------ */
/*  Main scaffold function                                             */
/* ------------------------------------------------------------------ */

/**
 * Scaffold a Next.js application from the project's requirements tree.
 *
 * Maps the ARQITEKT metamodel to a Next.js 15 file structure:
 *   BC  → Landing page (src/app/page.tsx)
 *   SOL → Route group  (src/app/<sol-slug>/)
 *   US  → Page          (src/app/<sol-slug>/<us-slug>/page.tsx)
 *   CMP → Component     (src/components/<cmp-slug>.tsx)
 *   FN  → Utility       (src/lib/<fn-slug>.ts)
 */
export async function scaffoldProject(
  projectId: string,
  force = false
): Promise<ScaffoldResult> {
  const projectPath = await resolveProjectById(projectId);
  const appPath = join(projectPath, 'app');
  const srcPath = join(appPath, 'src');
  const logs: string[] = [];
  let filesCreated = 0;

  // ------------------------------------------------------------------
  // Guard: check if app directory already exists
  // ------------------------------------------------------------------
  try {
    await stat(appPath);
    if (!force) {
      return {
        success: false,
        outputPath: appPath,
        filesCreated: 0,
        logs: ['App directory already exists. Use force=true to overwrite.'],
      };
    }
    logs.push('App directory exists — force mode, overwriting.');
  } catch {
    // App doesn't exist yet, proceed
  }

  // ------------------------------------------------------------------
  // Build requirements tree
  // ------------------------------------------------------------------
  const tree = await buildTree(projectId);
  logs.push(`Requirements tree loaded: ${tree.length} top-level node(s)`);

  // ------------------------------------------------------------------
  // Load branding from project config
  // ------------------------------------------------------------------
  const project = await getProjectById(projectId);
  const brand: Branding = {
    primary: project?.config.branding?.primaryColor ?? '#FFD700',
    secondary: project?.config.branding?.secondaryColor ?? '#1F1F1F',
  };

  // Identify BC and SOL nodes
  const bcNode = tree.find((n) => n.type === 'BC') ?? null;
  const solNodes: TreeNode[] = bcNode
    ? bcNode.children.filter((c) => c.type === 'SOL')
    : tree.filter((n) => n.type === 'SOL');

  const projectName = projectId
    .replace(/^\d{3}_/, '')
    .replace(/_/g, ' ');

  logs.push(
    `Project: "${projectName}" — BC: ${bcNode ? 'yes' : 'none'}, SOLs: ${solNodes.length}`
  );

  // ------------------------------------------------------------------
  // Helper to track file writes
  // ------------------------------------------------------------------
  async function write(filePath: string, content: string): Promise<void> {
    await writeFileWithDir(filePath, content, logs);
    filesCreated++;
  }

  // ------------------------------------------------------------------
  // Root config files
  // ------------------------------------------------------------------
  await write(join(appPath, 'package.json'), genPackageJson(projectName));
  await write(join(appPath, 'tsconfig.json'), genTsConfig());
  await write(join(appPath, 'next.config.mjs'), genNextConfig());
  await write(join(appPath, '.gitignore'), genGitignore());

  // ------------------------------------------------------------------
  // Global styles
  // ------------------------------------------------------------------
  await write(join(srcPath, 'app', 'globals.css'), genGlobalsCSS(brand));

  // ------------------------------------------------------------------
  // Root layout (with nav linking to all SOLs)
  // ------------------------------------------------------------------
  await write(
    join(srcPath, 'app', 'layout.tsx'),
    genRootLayout(projectName, solNodes)
  );

  // ------------------------------------------------------------------
  // Landing page from BC
  // ------------------------------------------------------------------
  const bcTitle = bcNode ? bcNode.title : projectName;
  await write(
    join(srcPath, 'app', 'page.tsx'),
    genLandingPage(projectName, bcTitle)
  );

  // ------------------------------------------------------------------
  // Collect all CMPs and FNs for deduplication
  // ------------------------------------------------------------------
  const allCmps = new Map<string, { node: TreeNode; parentUS: TreeNode }>();
  const allFns = new Map<string, { node: TreeNode; parentCmp: TreeNode }>();

  // ------------------------------------------------------------------
  // Per-SOL route groups
  // ------------------------------------------------------------------
  for (const sol of solNodes) {
    const solSlug = slugify(sol.title);
    const solDir = join(srcPath, 'app', solSlug);

    // SOL layout
    await write(join(solDir, 'layout.tsx'), genSolLayout(sol));

    // SOL index page
    await write(join(solDir, 'page.tsx'), genSolIndexPage(sol));

    logs.push(`SOL "${sol.id}" → /${solSlug}/`);

    // Per-US pages
    const usNodes = sol.children.filter((c) => c.type === 'US');
    for (const us of usNodes) {
      const usSlug = slugify(us.title);
      const usDir = join(solDir, usSlug);

      await write(join(usDir, 'page.tsx'), genUSPage(us, sol));

      logs.push(`  US "${us.id}" → /${solSlug}/${usSlug}/`);

      // Collect CMPs from this US
      const cmpNodes = us.children.filter((c) => c.type === 'CMP');
      for (const cmp of cmpNodes) {
        const cmpSlug = slugify(cmp.title);
        if (!allCmps.has(cmpSlug)) {
          allCmps.set(cmpSlug, { node: cmp, parentUS: us });
        }

        // Collect FNs from this CMP
        const fnNodes = cmp.children.filter((c) => c.type === 'FN');
        for (const fn of fnNodes) {
          const fnSlug = slugify(fn.title);
          if (!allFns.has(fnSlug)) {
            allFns.set(fnSlug, { node: fn, parentCmp: cmp });
          }
        }
      }
    }
  }

  // ------------------------------------------------------------------
  // Component stubs (src/components/<cmp-slug>.tsx)
  // ------------------------------------------------------------------
  for (const [cmpSlug, { node: cmp }] of allCmps) {
    await write(
      join(srcPath, 'components', `${cmpSlug}.tsx`),
      genComponent(cmp)
    );
    logs.push(`  CMP "${cmp.id}" → src/components/${cmpSlug}.tsx`);
  }

  // ------------------------------------------------------------------
  // Function stubs (src/lib/<fn-slug>.ts)
  // ------------------------------------------------------------------
  for (const [fnSlug, { node: fn, parentCmp }] of allFns) {
    await write(
      join(srcPath, 'lib', `${fnSlug}.ts`),
      genFunction(fn, parentCmp)
    );
    logs.push(`  FN "${fn.id}" → src/lib/${fnSlug}.ts`);
  }

  // ------------------------------------------------------------------
  // Summary
  // ------------------------------------------------------------------
  logs.push('');
  logs.push(`Scaffold complete: ${filesCreated} files created`);
  logs.push(`  SOLs: ${solNodes.length}`);
  logs.push(`  US pages: ${solNodes.reduce((n, s) => n + s.children.filter((c) => c.type === 'US').length, 0)}`);
  logs.push(`  Components: ${allCmps.size}`);
  logs.push(`  Functions: ${allFns.size}`);

  return {
    success: true,
    outputPath: appPath,
    filesCreated,
    logs,
  };
}
