// @generated — ARQITEKT Scaffold
// Root Layout — Social
import type { Metadata } from 'next';
import './globals.css';
import styles from './layout.module.css';

export const metadata: Metadata = {
  title: 'Social',
  description: 'Generated by ARQITEKT Product Factory',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de">
      <body>
        <header className={styles.header}>
          <h1 className={styles.logo}>Social</h1>
          <nav className={styles.nav}>
          <a href="/sol-10" className={styles.navLink}>SOL-10: Personality and Values Assessm...</a>
          <a href="/sol-11" className={styles.navLink}>SOL-11: Cooldown / Deceleration Mechan...</a>
          <a href="/sol-12" className={styles.navLink}>SOL-12: Detailed Intention Declaration</a>
          <a href="/sol-13" className={styles.navLink}>SOL-13: Trust and Seriousness System</a>
          <a href="/sol-14" className={styles.navLink}>SOL-14: Inactivity Management</a>
          <a href="/sol-15" className={styles.navLink}>SOL-15: Feedback Loop After Match Reje...</a>
          <a href="/sol-16" className={styles.navLink}>SOL-16: Staged Profile Release --- 3 V...</a>
          <a href="/sol-17" className={styles.navLink}>SOL-17: Exit Interview on Account Dele...</a>
          <a href="/sol-1" className={styles.navLink}>SOL-1: Verified Registration & Identi...</a>
          <a href="/sol-2" className={styles.navLink}>SOL-2: 5-Level Funnel Profile & Searc...</a>
          <a href="/sol-3" className={styles.navLink}>SOL-3: Intelligent Text-Based Matchin...</a>
          <a href="/sol-4" className={styles.navLink}>SOL-4: Optional Visual Harmony Matchi...</a>
          <a href="/sol-5" className={styles.navLink}>SOL-5: Mutual Consent Before Contact</a>
          <a href="/sol-6" className={styles.navLink}>SOL-6: Limited/Paid Reconfiguration +...</a>
          <a href="/sol-7" className={styles.navLink}>SOL-7: Data Protection and Security C...</a>
          <a href="/sol-8" className={styles.navLink}>SOL-8: Guided Reflective Onboarding A...</a>
          <a href="/sol-9" className={styles.navLink}>SOL-9: Compatibility Reflection "Why ...</a>
          </nav>
        </header>
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
  );
}
